name: Demo-Workflow
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - uses: actions/checkout@master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::072297576584:role/github-actions-demo-role
          aws-region: eu-west-1
      - name: List s3
        run: |
          aws s3 ls